author = Federico Fiorani and Artur Tarassow
email = deferoci@gmail.com
version = 1.0
date = 2022-08-07
description = Plot candlestick chart
tags = C10 C58
min-version = 2021d
public = plot_candlesticks
help = candlesticks_help.txt
sample-script = candlesticks_sample.inp
data-requirement = needs-time-series-data
data-files = cocacola.gdt
